services:
  - type: web
    name: pulse-financial-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_monochrome:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 